In [4]:
import numpy as np

In [5]:
arr1 = np.array([1,2,3,4,5])

In [6]:
arr1.shape

(5,)

In [7]:
arr1.dtype

dtype('int32')

In [8]:
arr1.ndim

1

In [9]:
arr1 = np.array([1,2,3,4,5], dtype=np.float)

In [10]:
arr1.dtype

dtype('float64')

In [11]:
arr2 = np.arange(0,10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr3 = np.arange(0,10,1.5)
arr3

array([0. , 1.5, 3. , 4.5, 6. , 7.5, 9. ])

In [13]:
arr_random = np.random.random((10,))

In [14]:
arr_random

array([0.12152449, 0.62168774, 0.37105214, 0.52833395, 0.96573215,
       0.33996062, 0.72803168, 0.03291132, 0.43763172, 0.92693444])

In [15]:
arr2_sqrt = np.sqrt(arr2)

In [16]:
arr2_sqrt

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [20]:
arr1 = np.arange(10,20)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [21]:
arr1 + arr2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [22]:
arr1*arr2

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [24]:
arr1**2

array([100, 121, 144, 169, 196, 225, 256, 289, 324, 361], dtype=int32)

In [26]:
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [28]:
arr1.max()

19

In [29]:
arr1.mean()

14.5

In [30]:
arr1.sum()

145

In [31]:
arr1.std()

2.8722813232690143

In [32]:
arr1 > 14

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [33]:
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [34]:
np.insert(arr1, 5, 10)

array([10, 11, 12, 13, 14, 10, 15, 16, 17, 18, 19])

In [35]:
np.delete(arr1,5)

array([10, 11, 12, 13, 14, 16, 17, 18, 19])

In [37]:
arr4 = np.array([1,10,5,33,3])
np.sort(arr4)

array([ 1,  3,  5, 10, 33])

In [38]:
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [39]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
arr = np.concatenate((arr1, arr2))
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9])

In [41]:
arr[(arr < 5)]

array([0, 1, 2, 3, 4])

In [42]:
arr[(arr < 10) & (arr > 5)]

array([6, 7, 8, 9])

In [44]:
arr[(arr < 3) | (arr > 17)]

array([18, 19,  0,  1,  2])

In [45]:
matrix1 = np.array([(1,2,3),(4,5,6),(7,8,9)])
matrix1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
matrix1.shape

(3, 3)

In [47]:
matrix1.ndim

2

In [48]:
matrix1.size

9

In [49]:
matrix1.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [50]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [51]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [52]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
np.full((3,3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [54]:
np.empty((3,3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [55]:
matrix2 = np.array([(10,11,12),(13,14,15),(16,17,18)])
matrix2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [56]:
matrix1 + matrix2

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [57]:
np.delete(matrix1, 2, axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
matrix2[1,2]

15